name: Build code0-flow crate

on:
  push:

jobs:
  crates:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: build/rust

    steps:
      - uses: actions/checkout@v4
      - name: Setup rust
        run: rustup update --no-self-update stable
      - name: Install protoc
        run: curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v28.0-rc1/protoc-28.0-rc-1-linux-x86_64.zip && unzip protoc-28.0-rc-1-linux-x86_64.zip -d ${{ runner.temp }}/proto && chmod +x ${{ runner.temp }}/proto/bin/protoc && ${{ runner.temp }}/proto/bin/protoc --version
      - name: Build crate
        run: PATH=${{ runner.temp }}/proto/bin:$PATH cargo build
        env:
          RUST_BACKTRACE: 'full'
      - name: Test De/Serialization from/to json
        run: PATH=${{ runner.temp }}/proto/bin:$PATH cargo test --features all
        env:
          RUST_BACKTRACE: 'full'
      - name: Package crate
        run: cargo package --allow-dirty