name: Publish code0-flow crate

on:
  push:
    tags:
      - '*'

jobs:
  crates:
    runs-on: ubuntu-latest

    environment: packages

    defaults:
      run:
        shell: bash

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Setup rust
        run: rustup update --no-self-update stable
      - name: Install protoc
        run: curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v28.0-rc1/protoc-28.0-rc-1-linux-x86_64.zip && unzip protoc-28.0-rc-1-linux-x86_64.zip -d ${{ runner.temp }}/proto && chmod +x ${{ runner.temp }}/proto/bin/protoc && ${{ runner.temp }}/proto/bin/protoc --version
      - name: Set version
        run: sed -i "s/version = \"0.0.0\"/version = \"${{ github.ref_name }}\"/" Cargo.toml
      - name: Cargo Login
        run: cargo login ${{secrets.CARGO_REGISTRY_TOKEN}}
      - name: Build crate
        run: PATH=${{ runner.temp }}/proto/bin:$PATH cargo build
        env:
          RUST_BACKTRACE: 'full'

      # Release
      - name: Publish crate
        run: cargo publish --allow-dirty